# @package _global_

# runs with execution time profiling

defaults:
  - default

trainer:
  max_epochs: 1
  accelerator: cpu
  profiler:
    _target_: lightning.pytorch.profilers.SimpleProfiler 
    dirpath: ${paths.output_dir}/profiler
    filename: simple_profiler

data:
  batch_size: 16
  num_workers: 0
  pin_memory: False
  drop_last: True
  persistent_workers: False
  sampler: null

model:
  scheduler: null