# @package _global_

# runs with execution time profiling

trainer:
  max_epochs: 10
  check_val_every_n_epoch: 10
  profiler:
    _target_: lightning.pytorch.profilers.SimpleProfiler
    dirpath: ${paths.output_dir}/profiler
    filename: simple_profiler

data:
  drop_last: False
