########################################################################
# General Settings
########################################################################

seed: 123
shapenet_folder: /shared/data/ShapeNetCore/Chair/03001627
root_path: /home/borth/sketch2shape
data_path: ${root_path}/data
checkpoint_path: ${root_path}/checkpoint


########################################################################
# Model Setting
########################################################################

embedding_size: 32
margin: 0.005
type_of_triplets: all

# only used for debugging dataloading
dummy_decoder: False
model_size_in_gb: null

########################################################################
# Trainer Settings
########################################################################

trainer:
  _target_: lightning.pytorch.trainer.Trainer
  accelerator: cpu
  profiler: simple
  max_epochs: 1
  val_check_interval: 10
  # limit_val_batches: 0
  enable_checkpointing: True
  log_every_n_steps: 1

monitor: train/loss
tags: ["siamese"]
learning_rate: 1e-03
weight_decay: 1e-04
early_stopping_patience: 3

########################################################################
# Data Settings
########################################################################

batch_size: 64
samples_per_class: 16
iteration_length: 10000

num_workers: 0
pin_memory: False
drop_last: True

########################################################################
# Default Settings
########################################################################

defaults:
  - _self_
  # - profiler: null
  - data: shapenet_chairs_sketch_large
  - logging: wandb # wandb, disabled
  - callbacks:
    - early_stopping
    - model_checkpoint
    - model_summary
  - model: siamese 
  - optional local: defaults

########################################################################
# Hydra Settings
########################################################################

hydra:
  run:
    dir: ${root_path}/wandb/hydra