########################################################################
# General Settings
########################################################################

seed: 123
shapenet_folder: /shared/data/ShapeNetCore/Chair/03001627
root_path: /home/borth/sketch2shape
data_path: ${root_path}/data
checkpoint_path: ${root_path}/checkpoint


########################################################################
# Model Setting
########################################################################

embedding_size: 32
margin: 0.2
type_of_triplets: semihard 

# only used for debugging dataloading
dummy_decoder: True
model_size_in_gb: 5

########################################################################
# Trainer Settings
########################################################################

trainer:
  _target_: lightning.pytorch.trainer.Trainer
  accelerator: gpu
  profiler: simple
  max_epochs: 1
  limit_val_batches: 0
  enable_checkpointing: False
  log_every_n_steps: 1

monitor: train/loss
learning_rate: 1e-03
weight_decay: 1e-04
early_stopping_patience: 3

########################################################################
# Data Settings
########################################################################

batch_size: 256
samples_per_class: 128
iteration_length: 10000

num_workers: 0
pin_memory: False
drop_last: True

########################################################################
# Default Settings
########################################################################

defaults:
  - _self_
  - data: shapenet_chairs_sketch_medium
  - logging: disabled # wandb, disabled
  - callbacks:
    - early_stopping
    - model_summary
  - model: siamese 

########################################################################
# Hydra Settings
########################################################################

hydra:
  run:
    dir: ${root_path}/wandb/hydra