########################################################################
# General Settings
########################################################################

seed: 42
root_path: /Users/korth/TUM/09/NiessnerLab/sketch2shape #/home/korth/sketch2shape
data_path: ${root_path}/data/deepsdf
checkpoint_path: ${root_path}/checkpoint/deepsdf

########################################################################
# Trainer Settings
########################################################################

trainer:
  _target_: lightning.pytorch.trainer.Trainer
  accelerator: cpu #gpu
  profiler: simple
  max_epochs: 500
  enable_checkpointing: True

### Dataloader
batch_size: 16384
num_workers: 1
drop_last: False
shuffle: True
persistent_workers: True

monitor: train/loss
dataset_name: shapenet_chair_single
early_stopping_patience: 1000
########################################################################
# Default Settings
########################################################################

defaults:
  - _self_
  - data: extract_sdf # shapenet13
  - logging: wandb # wandb, disabled
  - callbacks:
      # - early_stopping
      - model_checkpoint
  - model: deepsdf

########################################################################
# Hydra Settings
########################################################################

hydra:
  run:
    dir: ${root_path}/wandb/hydra
