########################################################################
# General Settings
########################################################################

seed: 42
root_path: /Users/robinborth/Code/sketch2shape #/home/korth/sketch2shape
data_path: ${root_path}/data/deepsdf
checkpoint_path: ${root_path}/checkpoint/deepsdf

########################################################################
# Model Setting
########################################################################

embedding_size: 512
num_hidden_layers: 8
loss:
  _target_: torch.nn.L1Loss
  reduction: mean


########################################################################
# Trainer Settings
########################################################################

trainer:
  _target_: lightning.pytorch.trainer.Trainer
  accelerator: cpu #gpu
  # profiler: simple
  max_epochs: 100
  enable_checkpointing: False

monitor: train/loss
learning_rate: 1e-04
early_stopping_patience: 10
tags: ["deep_sdf"]

########################################################################
# Data Settings
########################################################################

dataset_name: shapenet_chair_single
batch_size: 1024
num_workers: 9
drop_last: True
shuffle: True
persistent_workers: True

########################################################################
# Default Settings
########################################################################

defaults:
  - _self_
  - data: extract_sdf # shapenet13
  - logging: wandb # wandb, disabled
  - callbacks:
      - early_stopping
      # - model_checkpoint
  - model: deepsdf

########################################################################
# Hydra Settings
########################################################################

hydra:
  run:
    dir: ${root_path}/wandb/hydra
