########################################################################
# General Settings
########################################################################

seed: 42
root_path: /Users/robinborth/Code/sketch2shape #/home/korth/sketch2shape
data_path: ${root_path}/data/deepsdf
checkpoint_path: ${root_path}/checkpoint/deepsdf

########################################################################
# Model Setting
########################################################################

latent_size: 512
num_hidden_layers: 8
loss:
  _target_: torch.nn.L1Loss
  reduction: mean
latent_vector_size: 256
clamp: True
clamp_val: 0.1
reg_loss: True
num_scenes: 1
sigma: 1e-3
skip_connection: [4]
dropout_p: 0.2

########################################################################
# Data Settings
########################################################################

dataset:
  _target_: lib.data.dataset.DeepSDFDataset

dataset_name: shapenet_chair_single
load_ram: True
subsample: 65536

batch_size: 1
num_workers: 4
drop_last: True
shuffle: False
persistent_workers: True

########################################################################
# Optimizer Settings
########################################################################

lr_decoder: 1e-4
lr_latents: 1e-3

########################################################################
# Trainer Settings
########################################################################

trainer:
  _target_: lightning.pytorch.trainer.Trainer
  accelerator: gpu #gpu
  profiler: simple
  max_epochs: 20000
  enable_checkpointing: True
  log_every_n_steps: 1

monitor: train/loss

tags: ["deepsdf_overfitting_correct_sampling"]
group: "deepsdf"

########################################################################
# Default Settings
########################################################################

defaults:
  - _self_
  - data: extract_sdf # shapenet13
  - logging: wandb # wandb, disabled
  - callbacks:
      - model_summary
      # - lr_monitor
      - model_checkpoint
  - model: deepsdf
  - optional local: defaults

########################################################################
# Hydra Settings
########################################################################

hydra:
  run:
    dir: ${root_path}/wandb/hydra
