# @package _global_

defaults:
  - _self_
  - data: siamese_chair_small
  - hydra: default
  - paths: default
  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

# task name, determines output directory path
task_name: "data"

# seed for random number generators in pytorch, numpy and python.random
seed: 123