# @package _global_

defaults:
  - data: deepsdf_chair
  - trainer: default
  - logger: wandb
  # - logger: null
  - hydra: default
  - paths: default
  - debug: null
  - optional local: default
  - _self_

seed: 123
tags: ["deepsdf", "optimize_normals"]
task_name: optimize_normal
save_obj: True
save_obj_path: ${paths.root_dir}/temp 

trainer:
  accelerator: gpu
  max_epochs: 1000
  precision: 16-mixed
  log_every_n_steps: 1

model:
  _target_: lib.render.renderer.DeepSDFNormalRender
  ckpt_path: ${paths.root_dir}/logs/save/deepsdf.ckpt
  prior_idx: -1
  # prior_idx: 37
  reg_loss: False
  reg_weight: 1e-08
  image_weight: 1
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 1e-02
  scheduler:
    _partial_: True
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 500
    gamma: 0.1

data:
  _target_: lib.data.deepsdf_datamodule.RenderedSDFDataModule
  data_dir: ${paths.root_dir}/temp/data 
  num_workers: 7
  pin_memory: True
  persistent_workers: True
  drop_last: False
  dataset:
    _target_: lib.data.deepsdf_dataset.RenderedDataset
    _partial_: True

