# @package _global_

defaults:
  - data:
      - optimize_latent
  - model: optimize_sketch
  - trainer: default
  - logger: default
  - hydra: default
  - paths: default
  - debug: null
  - optional local: default
  - _self_

seed: 123
task_name: optimize_sketch
tags: ["optimize_sketch"]
train: True
eval: True
save_mesh: True
split: val
ckpt_path: ???

create_video: True
video_name: optimize_video.mp4
framerate: 30

trainer:
  num_sanity_val_steps: 0
  max_epochs: 5
  accumulate_grad_batches: 8

data:
  train_dataset:
    _target_: lib.data.deepsdf_dataset.SketchLatentOptimizerDataset
    azims: ${data.preprocess_siamese.azims}
    elevs: ${data.preprocess_siamese.elevs}