# @package _global_

defaults:
  - data:
    - optimize_latent
  - model: normals_render 
  - trainer: default
  - logger: null
  - hydra: default
  - paths: default
  - debug: null
  - optional local: default
  - _self_

seed: 123
task_name: optimize_normals
tags: ["optimize_normals"]
train: True 
eval: True
save_mesh: True
ckpt_path: ???

trainer:
  num_sanity_val_steps: 0

data:
  train_dataset:
    _target_: lib.data.deepsdf_dataset.NormalLatentOptimizerDataset
    azims: ${data.preprocess_siamese.azims}
    elevs: ${data.preprocess_siamese.elevs}