# @package _global_

defaults:
  - _self_
  - data:
    - shapenet_chair_1
    - optimize_latent
  - trainer: default
  - logger: null
  - hydra: default
  - paths: default
  - debug: null
  - optional local: default

seed: 123
task_name: optimize_normals
tags: ["deepsdf", "optimize_normals"]
save_obj: True
save_obj_path: ${paths.root_dir}/temp 

trainer:
  accelerator: gpu
  max_epochs: 500
  log_every_n_steps: 1

model:
  _target_: lib.render.renderer.DeepSDFNormalRender
  ckpt_path: /home/borth/sketch2shape/logs/train_deepsdf/runs/2024-01-15_12-50-49/checkpoints/last.ckpt
  prior_idx: 0
  reg_loss: True
  reg_weight: 1e-05
  normal_weight: 1.0
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 1e-02
  scheduler:
    _partial_: True
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 100
    gamma: 0.5

data:
  num_workers: 7
  pin_memory: True
  persistent_workers: True
  drop_last: False
  train_dataset:
    _target_: lib.data.deepsdf_dataset.NormalLatentOptimizerDataset
    azims: ${data.preprocess_siamese.azims}
    elevs: ${data.preprocess_siamese.elevs}