# @package _global_

defaults:
  - data:
      - optimize_latent
  - model: optimize_sketch
  - trainer: default
  - logger: default
  - hydra: default
  - paths: default
  - debug: null
  - optional local: default
  - _self_

seed: 123
task_name: optimize_sketch
tags: ["optimize_sketch"]
split: val
obj_ids: ???
train: True
prior_idx: False
eval: True
save_mesh: True
create_video: True
ckpt_path: ???


trainer:
  num_sanity_val_steps: 0
  max_epochs: 1
  accumulate_grad_batches: 8

data:
  train_dataset:
    _target_: lib.data.deepsdf_dataset.SketchLatentOptimizerDataset
    azims: ${data.preprocess_siamese.azims}
    elevs: ${data.preprocess_siamese.elevs}