# @package _global_

defaults:
  - data:
    - optimize_latent 
  - model: optimize_deepsdf
  - trainer: default
  - logger: null
  - hydra: default
  - paths: default
  - debug: null
  - optional local: default
  - _self_

seed: 123
task_name: optimize_deepsdf
tags: ["optimize_deepsdf"]
train: True 
test: True
save_mesh: True
split: val
ckpt_path: ???

trainer:
  num_sanity_val_steps: 0

data:
  train_dataset:
    _target_: lib.data.deepsdf_dataset.DeepSDFLatentOptimizerDataset
    chunk_size: 16384
    half: False
