# @package _global_

defaults:
  - data:
    - train_siamese
    - eval_siamese
  - model: siamese 
  - callbacks: default
  - logger: null 
  - trainer: default
  - hydra: default
  - paths: default
  - optional local: default
  - experiement: null
  - debug: null
  - _self_

seed: 123
task_name: train_siamese
tags: ["train_siamese"]
train: True
eval: True
ckpt_path: null

trainer:
  max_epochs: 100
  val_check_interval: 120 

callbacks:
  early_stopping:
    monitor: val/loss
    patience: 40