# @package _global_

defaults:
  - data:
    - train_loss
    - eval_loss
  - dataset: shapenet_chair_4096
  - model: latent_siamese 
  - callbacks: 
    - default
    - early_stopping
  - logger: default 
  - trainer: default
  - hydra: default
  - paths: default
  - optional local: default
  - experiement: null
  - debug: null
  - _self_

seed: 123
task_name: train_loss
tags: ["train_loss"]
train: True
eval: False
ckpt_path: ???
loss_ckpt_path: ???
deepsdf_ckpt_path: ???

trainer:
  max_epochs: 20
  val_check_interval: 0.25

callbacks:
  model_checkpoint:
    save_top_k: -1
    every_n_epochs: 1
    save_last: True
  # stop if no improvement after one full epoch
  early_stopping:  
    monitor: val/loss
    patience: 4
