# @package _global_

defaults:
  - data:
    - train_deepsdf 
  - model: deepsdf
  - callbacks: default
  - logger: null 
  - trainer: default
  - hydra: default
  - paths: default
  - optional local: default
  - experiement: null
  - debug: null
  - _self_

seed: 123
task_name: train_deepsdf
tags: ["train_deepsdf"]
train: True
ckpt_path: null
