# @package model

_target_: lib.models.traverse_latent.DeepSDFSNNLatentTraversal
ckpt_path: ${ckpt_path} 
siamese_ckpt_path: ${siamese_ckpt_path}
data_dir: ${data.data_dir}
std: 1e-01
prior_idx_start: -1
prior_idx_end: -1
create_video: ${create_video}
image_resolution: 256
mesh_resolution: 128
mesh_chunk_size: 65536
video_azim: 40 
video_elev: -30