# @package model
_target_: lib.models.deepsdf.DeepSDF

# learning settings
decoder_lr: 5e-04
latents_lr: 1e-03
reg_loss: True
reg_weight: 1e-4
clamp: True
clamp_val: 0.1
adaptive_sample_strategy: False
adaptive_mining_strategy: False
scheduler: null
# model settings
latent_size: 512
num_hidden_layers:  8
latent_vector_size:  256
num_latent_vectors: ${data.num_obj_train}
skip_connection: [4]
weight_norm: True
dropout: 0.2
# mesh settings
mesh_resolution: 128
mesh_chunk_size: 65536
# rendering settings
n_render_steps: 100
clamp_sdf: 0.1
step_scale: 1.0
surface_eps: 1e-03
sphere_eps: 1e-01
normal_eps: 5e-03