# @package model

_target_: lib.models.optimize_sketch.DeepSDFSketchRender
ckpt_path: ${ckpt_path}
siamese_ckpt_path: ${siamese_ckpt_path}
prior_idx: -1
reg_loss: True
reg_weight: 1e-02
siamese_weight: 100
step_scale: 1.0
image_resolution: 256
mesh_resolution: 256
mesh_chunk_size: 65536
video_capture_rate: 8
video_azim: 30
video_elev: 15
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-02
scheduler:
  _partial_: True
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 5 
  gamma: 0.5

