# @package model

_target_: lib.optimize.deepsdf.DeepSDFLatentOptimizer
ckpt_path: ${ckpt_path} 
prior_idx: -1
obj_id: "" 
reg_loss: True
reg_weight: 1e-05
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-02
scheduler:
  _partial_: True
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 100
  gamma: 0.5
# mesh settings
mesh_resolution: 128
mesh_chunk_size: 65536
# rendering settings
capture_rate: 30
n_render_steps: 100
clamp_sdf: 0.1
step_scale: 1.0
surface_eps: 1e-03
sphere_eps: 1e-01
normal_eps: 5e-03