# @package model
_target_: lib.models.siamese.Siamese
decoder:
  _target_: lib.models.decoder.ResNet18
  _partial_: true
  embedding_size: 128
  pretrained: True 
miner:
  _target_: pytorch_metric_learning.miners.TripletMarginMiner
  _partial_: true
  margin: 0.2
  type_of_triplets: semihard
regularizer:
  _target_: pytorch_metric_learning.regularizers.LpRegularizer
  _partial_: true
  power: 1
loss:
  _target_: pytorch_metric_learning.losses.TripletMarginLoss
  _partial_: true
  margin: 1.0
  swap: False
  smooth_loss: False
  triplets_per_anchor: all
  reducer: 
    _target_: pytorch_metric_learning.reducers.AvgNonZeroReducer 
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 10
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-03 
  weight_decay: 0.0