# @package model
_target_: lib.models.siamese.Siamese
embedding_size: 128
pretrained: True 
reg_loss: True 
reg_weight: 1e-01
margin: 1.0 
lr_head: 1e-03
lr_backbone: 1e-05
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 10