# @package model

_target_: lib.models.traverse_latent.DeepSDFLatentTraversal
ckpt_path: ${ckpt_path} 
prior_idx_start: -1
prior_idx_end: 0
create_mesh: ${create_mesh}
create_video: ${create_video}
# snn loss
compute_snn_loss: False
siamese_ckpt_path: ${siamese_ckpt_path} 
data_dir: ${data.data_dir}
# mesh settings
mesh_resolution: 128
mesh_chunk_size: 65536
# rendering settings
capture_rate: 30
n_render_steps: 100
clamp_sdf: 0.1
step_scale: 1.0
surface_eps: 1e-03
sphere_eps: 1e-01
normal_eps: 5e-03