# @package model

_target_: lib.models.traverse_latent.DeepSDFLatentTraversal
ckpt_path: ${ckpt_path} 
prior_idx: -1
prior_idx_start: -1
prior_idx_end: -1
image_resolution: 256
mesh_resolution: 128
mesh_chunk_size: 65536